Task/sc 1101/node js 12 deprecation
epcpower/sunspec-demo pull request #28
Opened 2023-04-05 19:28 UTC by Fabian6781

## Jira Story
SC-1050

## About

1. actions/checkout@v2 -> actions/checkout@v3
2. actions/setup-python@v1 -> actions/setup-python@v4
3. aws-actions/configure-aws-credentials@v1 -> aws-actions/configure-aws-credentials@v1-node16

## Associated Pull Requests
N/A

## Update Changelog

* [X] Changelog updated

## Reproduction Steps

## Validation

2023-04-06 01:27 UTC, gordon-epc requested changes

2023-04-06 01:27 UTC, gordon-epc commented on .github/workflows/ci.yml
Looks like this one was missed:
`actions/upload-artifact@v2`

2023-05-08 23:11 UTC, gordon-epc requested changes

2023-05-08 23:11 UTC, gordon-epc commented on CHANGELOG.md
> +- SC-1101: Update ci.yml actions to fix poetry version issue
Let's use the same changelog message as the original grid-tied fix.
```suggestion
- SC-1101: Pin versions of all python packages for installing poetry
```

2023-05-08 23:11 UTC, gordon-epc commented on .github/workflows/ci.yml
> +          #install Poetry
Not necessary, as the `name` above says the same thing.
```suggestion
```

2023-05-09 18:21 UTC, Fabian6781 commented on CHANGELOG.md
> +- SC-1101: Update ci.yml actions to fix poetry version issue
Done.

2023-05-09 18:27 UTC, gordon-epc approved these changes

2023-05-09 19:18 UTC, merged